from __future__ import annotations

from contexthub.ui.qt.shell import CollapsibleSection, get_shell_metrics
from features.versus_up.versus_up_qt_widgets import RadarCompareWidget

try:
    from PySide6.QtCore import Qt
    from PySide6.QtWidgets import (
        QAbstractItemView,
        QCheckBox,
        QComboBox,
        QFrame,
        QHBoxLayout,
        QGridLayout,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QPlainTextEdit,
        QPushButton,
        QScrollArea,
        QSlider,
        QStackedLayout,
        QTableWidget,
        QVBoxLayout,
        QWidget,
    )
except ImportError as exc:  # pragma: no cover
    raise ImportError("PySide6 is required for versus_up.") from exc


class MatrixTableWidget(QTableWidget):
    def keyPressEvent(self, event) -> None:  # noqa: N802
        key = event.key()
        if key in (Qt.Key_Left, Qt.Key_Right, Qt.Key_Up, Qt.Key_Down):
            row = self.currentRow()
            column = self.currentColumn()
            if self.rowCount() >= 3 and self.columnCount() >= 3:
                if row <= 0:
                    row = 1
                elif row >= self.rowCount() - 1:
                    row = self.rowCount() - 2
                if column <= 0:
                    column = 1
                elif column >= self.columnCount() - 1:
                    column = self.columnCount() - 2
                if key == Qt.Key_Left:
                    column = max(1, column - 1)
                elif key == Qt.Key_Right:
                    column = min(self.columnCount() - 2, column + 1)
                elif key == Qt.Key_Up:
                    row = max(1, row - 1)
                elif key == Qt.Key_Down:
                    row = min(self.rowCount() - 2, row + 1)
                self.setCurrentCell(row, column)
                return
        super().keyPressEvent(event)


class HistoryPanel(QFrame):
    def __init__(self) -> None:
        super().__init__()
        self.setObjectName("subtlePanel")
        layout = QVBoxLayout(self)
        layout.setContentsMargins(12, 12, 12, 12)
        layout.setSpacing(10)
        title = QLabel("History")
        title.setObjectName("sectionTitle")
        self.recent_list = QListWidget()
        self.recent_list.setMinimumHeight(210)
        self.recent_list.setAlternatingRowColors(False)
        self.preset_list = QListWidget()
        self.preset_list.setMinimumHeight(210)
        self.preset_list.setAlternatingRowColors(False)
        self.current_project_label = QLabel("No project loaded")
        self.current_project_label.setObjectName("muted")
        self.current_project_label.setWordWrap(True)
        project_actions = QHBoxLayout()
        project_actions.setSpacing(8)
        self.add_preset_btn = QPushButton("Preset")
        self.add_preset_btn.setMaximumWidth(92)
        self.project_menu_btn = QPushButton("More")
        self.project_menu_btn.setMaximumWidth(84)
        project_actions.addStretch(1)
        project_actions.addWidget(self.add_preset_btn)
        project_actions.addWidget(self.project_menu_btn)
        tab_row = QHBoxLayout()
        self.recent_tab_btn = QPushButton("Recent")
        self.recent_tab_btn.setObjectName("primary")
        self.presets_tab_btn = QPushButton("Presets")
        tab_row.addWidget(self.recent_tab_btn)
        tab_row.addWidget(self.presets_tab_btn)
        tab_row.addStretch(1)
        list_host = QWidget()
        self.list_stack = QStackedLayout(list_host)
        self.list_stack.setContentsMargins(0, 0, 0, 0)
        self.list_stack.addWidget(self.recent_list)
        self.list_stack.addWidget(self.preset_list)
        self.remove_preset_btn = QPushButton("Delete preset")
        self.remove_preset_btn.setMaximumWidth(120)
        action_row = QHBoxLayout()
        self.new_btn = QPushButton("New")
        self.open_btn = QPushButton("Open")
        self.open_btn.setObjectName("primary")
        action_row.addWidget(self.new_btn)
        action_row.addWidget(self.open_btn)
        layout.addWidget(title)
        layout.addWidget(self.current_project_label)
        layout.addLayout(project_actions)
        layout.addLayout(tab_row)
        layout.addWidget(list_host, 1)
        layout.addWidget(self.remove_preset_btn, 0, Qt.AlignRight)
        layout.addLayout(action_row)


class WorkspacePanel(QFrame):
    def __init__(self) -> None:
        super().__init__()
        m = get_shell_metrics()
        self.setObjectName("card")
        layout = QVBoxLayout(self)
        layout.setContentsMargins(m.panel_padding, m.panel_padding, m.panel_padding, m.panel_padding)
        layout.setSpacing(10)
        matrix_head = QHBoxLayout()
        matrix_title = QLabel("Comparison Matrix")
        matrix_title.setObjectName("sectionTitle")
        title_stack = QVBoxLayout()
        title_stack.setSpacing(2)
        title_stack.addWidget(matrix_title)
        self.matrix_context_label = QLabel("")
        self.matrix_context_label.setObjectName("muted")
        self.matrix_context_label.setWordWrap(True)
        title_stack.addWidget(self.matrix_context_label)
        matrix_head.addLayout(title_stack)
        matrix_head.addStretch(1)
        self.matrix_table = MatrixTableWidget()
        self.matrix_table.horizontalHeader().hide()
        self.matrix_table.verticalHeader().hide()
        self.matrix_table.setShowGrid(True)
        self.matrix_table.setCornerButtonEnabled(False)
        self.matrix_table.setSelectionMode(QAbstractItemView.SingleSelection)
        self.matrix_table.setSelectionBehavior(QAbstractItemView.SelectItems)
        self.matrix_table.setEditTriggers(QAbstractItemView.DoubleClicked | QAbstractItemView.EditKeyPressed | QAbstractItemView.AnyKeyPressed)
        layout.addLayout(matrix_head)
        layout.addWidget(self.matrix_table, 1)


class CompareSummaryPanel(QFrame):
    def __init__(self) -> None:
        super().__init__()
        self.setObjectName("subtlePanel")
        layout = QVBoxLayout(self)
        layout.setContentsMargins(12, 12, 12, 12)
        layout.setSpacing(8)
        title = QLabel("Radar Compare")
        title.setObjectName("sectionTitle")
        self.subtitle = QLabel("")
        self.subtitle.setObjectName("muted")
        self.subtitle.setWordWrap(True)
        self.radar = RadarCompareWidget()
        layout.addWidget(title)
        layout.addWidget(self.subtitle)
        layout.addWidget(self.radar, 1)


class CriterionDetailPanel(QFrame):
    def __init__(self) -> None:
        super().__init__()
        self.setObjectName("subtlePanel")
        layout = QVBoxLayout(self)
        layout.setContentsMargins(12, 12, 12, 12)
        layout.setSpacing(8)
        self.title = QLabel("Selection")
        self.title.setObjectName("sectionTitle")
        self.mode_label = QLabel("Select a product or criterion")
        self.mode_label.setObjectName("eyebrow")
        self.selected_product_label = QLabel("Product: -")
        self.selected_product_label.setObjectName("eyebrow")
        self.selected_criterion_label = QLabel("Criterion: -")
        self.selected_criterion_label.setObjectName("eyebrow")
        self.product_section = QWidget()
        self.product_form = QVBoxLayout(self.product_section)
        self.product_form.setContentsMargins(0, 0, 0, 0)
        self.product_form.setSpacing(10)
        self.product_header_row = QHBoxLayout()
        self.product_header_row.setSpacing(8)
        self.product_favorite_box = QCheckBox("Pin")
        self.product_favorite_box.setObjectName("eyebrow")
        self.product_header_row.addStretch(1)
        self.product_header_row.addWidget(self.product_favorite_box, 0, Qt.AlignRight)
        self.product_preview_card = QFrame()
        self.product_preview_card.setObjectName("card")
        self.product_preview_card.setMinimumHeight(280)
        preview_layout = QVBoxLayout(self.product_preview_card)
        preview_layout.setContentsMargins(12, 12, 12, 12)
        preview_layout.setSpacing(8)
        self.product_thumbnail = QLabel("No image")
        self.product_thumbnail.setAlignment(Qt.AlignCenter)
        self.product_thumbnail.setMinimumHeight(168)
        self.product_thumbnail.setMaximumHeight(192)
        self.product_thumbnail.setObjectName("subtlePanel")
        self.product_thumbnail.setWordWrap(True)
        self.product_thumbnail.setScaledContents(False)
        self.product_thumbnail.setCursor(Qt.PointingHandCursor)
        self.product_color_chip = QLabel("Accent")
        self.product_color_chip.setObjectName("eyebrow")
        self.product_color_chip.setAlignment(Qt.AlignCenter)
        self.product_color_chip.setMaximumWidth(96)
        preview_header = QHBoxLayout()
        preview_header.addWidget(self.product_color_chip, 0)
        preview_header.addStretch(1)
        preview_layout.addLayout(preview_header)
        preview_layout.addWidget(self.product_thumbnail)
        self.product_gallery_scroll = QScrollArea()
        self.product_gallery_scroll.setWidgetResizable(True)
        self.product_gallery_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.product_gallery_scroll.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.product_gallery_scroll.setFrameShape(QFrame.NoFrame)
        self.product_gallery_host = QWidget()
        self.product_gallery_layout = QGridLayout(self.product_gallery_host)
        self.product_gallery_layout.setContentsMargins(0, 0, 0, 0)
        self.product_gallery_layout.setHorizontalSpacing(8)
        self.product_gallery_layout.setVerticalSpacing(8)
        self.product_gallery_scroll.setWidget(self.product_gallery_host)
        self.product_gallery_scroll.setMaximumHeight(120)
        preview_layout.addWidget(self.product_gallery_scroll)
        self.product_media_row = QHBoxLayout()
        self.product_media_row.setSpacing(8)
        self.product_image_btn = QPushButton("Add images")
        self.product_remove_image_btn = QPushButton("Remove image")
        self.product_media_row.addWidget(self.product_image_btn, 1)
        self.product_media_row.addWidget(self.product_remove_image_btn, 1)
        self.product_action_row = QHBoxLayout()
        self.product_action_row.setSpacing(8)
        self.product_vision_btn = QPushButton("Run vision")
        self.product_vision_btn.setObjectName("primary")
        self.product_action_row.addWidget(self.product_vision_btn, 1)
        self.product_identity_card = QFrame()
        self.product_identity_card.setObjectName("subtlePanel")
        identity_layout = QGridLayout(self.product_identity_card)
        identity_layout.setContentsMargins(10, 10, 10, 10)
        identity_layout.setHorizontalSpacing(8)
        identity_layout.setVerticalSpacing(10)
        self.product_name_edit = QLineEdit()
        self.product_name_edit.setPlaceholderText("Product name")
        self.product_name_edit.setAlignment(Qt.AlignCenter)
        self.product_color_edit = QLineEdit()
        self.product_color_edit.setReadOnly(True)
        self.product_color_edit.hide()
        self.product_notes_edit = QPlainTextEdit()
        self.product_notes_edit.setMaximumHeight(84)
        self.product_notes_edit.setPlaceholderText("Why this model matters, trade-offs, or purchase notes.")
        self.product_delete_btn = QPushButton("Delete product")
        self.product_palette_row = QHBoxLayout()
        self.product_palette_row.setContentsMargins(0, 0, 0, 0)
        self.product_palette_row.setSpacing(10)
        self.product_color_buttons: list[QPushButton] = []
        palette_host = QWidget()
        palette_host.setLayout(self.product_palette_row)
        identity_layout.addWidget(QLabel("Name"), 0, 0)
        identity_layout.addWidget(self.product_name_edit, 0, 1)
        identity_layout.addWidget(QLabel("Palette"), 1, 0)
        identity_layout.addWidget(palette_host, 1, 1)
        identity_layout.addWidget(QLabel("Notes"), 2, 0)
        identity_layout.addWidget(self.product_notes_edit, 2, 1)
        delete_row = QHBoxLayout()
        delete_row.setSpacing(8)
        delete_row.addStretch(1)
        delete_row.addWidget(self.product_delete_btn, 0)
        self.product_form.addLayout(self.product_header_row)
        self.product_form.addWidget(self.product_preview_card)
        self.product_form.addLayout(self.product_media_row)
        self.product_form.addLayout(self.product_action_row)
        self.product_form.addWidget(self.product_identity_card)
        self.product_form.addLayout(delete_row)
        self.product_form.addStretch(1)
        self.criterion_section = QWidget()
        criterion_layout = QVBoxLayout(self.criterion_section)
        criterion_layout.setContentsMargins(0, 0, 0, 0)
        criterion_layout.setSpacing(10)
        self.criterion_card = QFrame()
        self.criterion_card.setObjectName("subtlePanel")
        form = QGridLayout(self.criterion_card)
        form.setContentsMargins(10, 10, 10, 10)
        form.setSpacing(8)
        self.criterion_label_edit = QLineEdit()
        self.criterion_description_edit = QPlainTextEdit()
        self.criterion_description_edit.setMaximumHeight(88)
        self.criterion_type_combo = QComboBox()
        self.criterion_type_combo.addItems(["number", "text"])
        self.criterion_direction_combo = QComboBox()
        self.criterion_direction_combo.addItems(["high", "low"])
        self.criterion_unit_edit = QLineEdit()
        self.criterion_include_box = QCheckBox("Reflect in final score")
        self.weight_value_label = QLabel("1.00")
        self.weight_value_label.setObjectName("eyebrow")
        self.criterion_weight_slider = QSlider(Qt.Horizontal)
        self.criterion_weight_slider.setRange(0, 500)
        form.addWidget(QLabel("Label"), 0, 0)
        form.addWidget(self.criterion_label_edit, 0, 1)
        form.addWidget(QLabel("Description"), 1, 0)
        form.addWidget(self.criterion_description_edit, 1, 1)
        form.addWidget(QLabel("Type"), 2, 0)
        form.addWidget(self.criterion_type_combo, 2, 1)
        form.addWidget(QLabel("Direction"), 3, 0)
        form.addWidget(self.criterion_direction_combo, 3, 1)
        form.addWidget(QLabel("Unit"), 4, 0)
        form.addWidget(self.criterion_unit_edit, 4, 1)
        form.addWidget(QLabel("Weight"), 5, 0)
        weight_row = QHBoxLayout()
        weight_row.addWidget(self.criterion_weight_slider, 1)
        weight_row.addWidget(self.weight_value_label, 0)
        form.addLayout(weight_row, 5, 1)
        form.addWidget(self.criterion_include_box, 6, 0, 1, 2)
        criterion_layout.addWidget(self.criterion_card)
        criterion_layout.addStretch(1)
        layout.addWidget(self.title)
        layout.addWidget(self.mode_label)
        layout.addWidget(self.selected_product_label)
        layout.addWidget(self.selected_criterion_label)
        self.detail_stack = QStackedLayout()
        self.detail_stack.addWidget(self.product_section)
        self.detail_stack.addWidget(self.criterion_section)
        stack_host = QWidget()
        stack_host.setLayout(self.detail_stack)
        layout.addWidget(stack_host, 1)


class ServerStatusPanel(CollapsibleSection):
    def __init__(self) -> None:
        super().__init__("Server Status", expanded=False)
        status_card = QFrame()
        status_card.setObjectName("subtlePanel")
        status_layout = QGridLayout(status_card)
        status_layout.setContentsMargins(10, 10, 10, 10)
        status_layout.setSpacing(8)
        self.server_runtime_label = QLabel("")
        self.server_runtime_label.setObjectName("eyebrow")
        self.server_last_error = QLabel("")
        self.server_last_error.setObjectName("muted")
        self.server_last_error.setWordWrap(True)
        self.ollama_host_edit = QLineEdit()
        self.vision_model_edit = QLineEdit()
        self.classifier_model_edit = QLineEdit()
        status_layout.addWidget(QLabel("Runtime"), 0, 0)
        status_layout.addWidget(self.server_runtime_label, 0, 1)
        status_layout.addWidget(QLabel("Ollama host"), 1, 0)
        status_layout.addWidget(self.ollama_host_edit, 1, 1)
        status_layout.addWidget(QLabel("Vision model"), 2, 0)
        status_layout.addWidget(self.vision_model_edit, 2, 1)
        status_layout.addWidget(QLabel("Classifier model"), 3, 0)
        status_layout.addWidget(self.classifier_model_edit, 3, 1)
        status_layout.addWidget(QLabel("Last issue"), 4, 0)
        status_layout.addWidget(self.server_last_error, 4, 1)
        self.add_widget(status_card)
        self.finish()
